### ISSUE TITLE
Fix hidelist

### ISSUE THREAD

**Issue by wanderingstan** [OriginProtocol/origin-dapp#416] opened 2018-08-17 16:32 UTC
As part of the 0.7.0 release, I [hit a snag merging our completed release branch into _master_,](https://github.com/OriginProtocol/origin-dapp/commit/6ff71f6dc52733def8e919be08d65c2bfd0a9c40) because we (er...I) had [done a hotfix](https://github.com/OriginProtocol/origin-dapp/pull/231) to master months ago changing our hidelist strategy back to using listing indexes. 

So right now on master we have (I think) the [hide-by-contract-address technique](https://github.com/OriginProtocol/origin-dapp/pull/231/files) that failed us with "the great kettle bell attack of 2018"

We need to sort this out and get a working hidelist going. 

Things seem to be working, but leaving this issue open.

**Comment by micahalcorn** [comment] 2018-09-05 15:35
Duplicate of https://github.com/OriginProtocol/origin-dapp/issues/443 ❓

**Closed by micahalcorn** 2018-09-05 15:35 UTC
Labels: dapp, javascript
