### ISSUE TITLE
No way for buyer to get refund if seller withdraws listing after accepting an offer

### ISSUE THREAD

**Issue by cuongdo** [OriginProtocol/origin-dapp#616] opened 2018-09-28 15:48 UTC
Steps:
1. Seller: create a listing
2. Buyer: make an offer
3. Seller: accept the offer
4. Seller: withdraw the listing
5. Buyer: visit "My Purchases" and click on the purchase for the withdrawn listing

At step 5, as the buyer, I expect to see a page that lets me withdraw the offer, so I can get my offer refunded to me. Even better would be an automatic refund when the seller withdraws a listing with an accepted offer. This would involve less work for the buyer, and it seems fair for the seller to pay the gas for the refund.

Instead, what I see when clicking on the purchase is:

![image](https://user-images.githubusercontent.com/1564582/46218880-c2839b80-c313-11e8-939d-8705666310d2.png)

The only indication that the listing has been withdrawn is somewhat hidden in the lower right corner of the purchase page:

![image](https://user-images.githubusercontent.com/1564582/46219035-3d4cb680-c314-11e8-8814-55d295c2160d.png)

**Comment by cuongdo** [comment] 2018-09-28 15:48
cc @micahalcorn @nick

**Comment by franckc** [comment] 2018-09-28 16:53
Is that a DApp UI change only or does this require a contract change as well ?

Quickly looking at the contract code, the [withdrawOffer](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/marketplace/v00/Marketplace.sol#L264) reads the listing from storage but when a listing is withdrawn, it does get deleted it from storage... See [code](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/marketplace/v00/Marketplace.sol#L171). So looks like that would be a problem... 

We could fix in DApp only by not allowing a seller to close a listing while there are accepted offers. But I would not be surprised this comes up during the auditing if we don't fix in contracts as well ?

**Comment by franckc** [comment] 2018-09-28 16:55
Marking as P0 for close tracking until we decide course of action.

**Comment by cuongdo** [comment] 2018-09-28 17:28
The contract supports refunding the buyer in this scenario.

**Comment by micahalcorn** [comment] 2018-09-28 17:31
One question is whether or not sellers should be able to withdraw listings that are subject to current offers. Right now, that is their only option to remove listings from public view. In the future, we will probably want the ability for a seller to update a listing with a new quantity available but leave it intact for future availability.

More generally, I don't think that buyers are supposed to be able to withdraw an offer after it is accepted, are they? In the case of a withdrawn listing, does the offer still "work"?

On a separate note, we have a long-term plan for replacing that status card that is "hidden" and misleading right now.

**Comment by nick** [comment] 2018-09-28 18:53
Yea the offer will still work if the listing is withdrawn.  A buyer can withdraw an offer a) if it has not yet been accepted or b) if it *has* been accepted, but the listing has been withdrawn. So it's not in the seller's interest to withdraw a listing unless any outstanding offers have been finalized.

On withdrawing a listing... right now that is only doable by the depositManager - but for version 1 the seller is also the depositManager. In the future, we could potentially have an Origin depositManager that will only let sellers withdraw listings if there are no open offers.

**Comment by micahalcorn** [comment] 2018-09-30 16:19
@nick in my experience testing this, the funds do not get released to the seller as I would expect.

**Steps To Reproduce**

1. Create Listing (User A)
1. Make Offer (User B)
1. Accept Offer (User A)
1. Close Listing (User A)
1. Complete Sale (User B)

In this scenario, with a listing price of 1.00000 ETH, User B's wallet balance is reduced by 1.00000 ETH + some gas and User A's wallet balance is lower than it was at the beginning (due to gas cost).

Also, all references to the seller now return `0x0000000000000000000000000000000000000000`, which is probably a secondary concern.

I can confirm that we don't want the buyer to be able to withdraw an accepted offer that the seller may be depending on. We can prevent the seller from withdrawing a listing that is subject to current offers via the DApp, but it seems like the contract may not be working as intended.

**Comment by micahalcorn** [comment] 2018-09-30 18:54
Due to the current UX confusion with statuses - close, [in]active, sold, pending, offered, accepted, disputed, etc - I think it’s reasonable to expect people to withdraw them in an effort to prevent other purchases or remove their listings from the home page.

I haven’t confirmed, but it sounds like our UI might also be broken in the event that a finalized offer’s listing is withdrawn.

**Comment by franckc** [comment] 2018-10-01 04:32
Since we are getting super close from our launch, I'd be inclined to go for the simplest option proposed by @nick which is to [not delete a listing from blockchain storage](https://github.com/OriginProtocol/origin-js/blob/master/contracts/contracts/marketplace/v00/Marketplace.sol#L171) when a seller withdraws. 

It means the seller will have to pay a little bit more gas to withdraw the listing (since we won't get gas back anymore for deleting data from storage), but imho that's totally acceptable for V1.

Does that sound good to everyone ?

**Comment by cuongdo** [comment] 2018-10-01 05:15
Not deleting the listing sounds good to me.

**Comment by nick** [comment] 2018-10-01 16:32
Pushed OriginProtocol/origin-js#581 to address this.

**Comment by franckc** [comment] 2018-10-02 06:11
Fixed by origin-js PR 581.

**Closed by franckc** 2018-10-02 06:11 UTC
Labels: dapp, p0, smart contracts
